Fix order_path issue in cart page
The order_path route wasn't being inferred correctly from this Spree controller, causing errors to be thrown in the cart page if the number of editable orders was precisely one:

ActionView::Template::Error: undefined method `order_path'