Add postcss-loader v3
Specify the version due to:

ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.

See: https://github.com/JeffreyWay/laravel-mix/issues/2471#issuecomment-689218687