Explicitly require Spree::Admin::BaseHelper
NameError: undefined method `preference_field_tag' for module `Spree::Admin::BaseHelper'
/home/runner/openfoodnetwork/vendor/bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method'
/home/runner/openfoodnetwork/vendor/bundle/ruby/2.3.0/gems/activesupport-4.0.13/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
/home/runner/openfoodnetwork/app/helpers/spree/admin/base_helper_decorator.rb:11:in `<module:BaseHelper>'
/home/runner/openfoodnetwork/app/helpers/spree/admin/base_helper_decorator.rb:3:in `<module:Admin>'