Use latest LTS Node version in CI
We have reason to believe that the very old Node version is the root
cause of the error:

```
Run yarn install --frozen-lockfile
/usr/share/yarn/lib/cli.js:46100
  let {
      ^

SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/usr/share/yarn/lib/v8-compile-cache.js:226:18)
    at Module._compile (/usr/share/yarn/lib/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```